# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "23102e16d4ffc1e5d75c7f7c6cfd7679"
application_url = "https://responsibilities-cop-neither-palace.trycloudflare.com"
embedded = true
name = "product persionalizer"
handle = "product-persionalizer"

[build]
include_config_on_deploy = true
dev_store_url = "urbann-curate.myshopify.com"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://responsibilities-cop-neither-palace.trycloudflare.com/auth/callback",
  "https://responsibilities-cop-neither-palace.trycloudflare.com/auth/shopify/callback",
  "https://responsibilities-cop-neither-palace.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
